-- SAMPLE 테이블 생성
CREATE TABLE SAMPLE (
    id number generated by default as identity,
    name varchar2(50) not null,
    email varchar2(100),
    created_at timestamp,
    updated_at timestamp,
    constraint pk_sample primary key (id)
) TABLESPACE STUDY;

-- SAMPLE 시퀀스 생성
CREATE SEQUENCE SAMPLE_SEQ START WITH 1 INCREMENT BY 1;